# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_dlg.ui'
#
# Created: Sun Oct 12 14:07:33 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(446, 608)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_2 = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(400, 130))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(8, 8, 35, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(50, 20, 31, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.dataPb = QtGui.QPushButton(self.frame_2)
        self.dataPb.setGeometry(QtCore.QRect(90, 20, 40, 22))
        self.dataPb.setMinimumSize(QtCore.QSize(40, 0))
        self.dataPb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dataPb.setObjectName(_fromUtf8("dataPb"))
        self.evVPb = QtGui.QPushButton(self.frame_2)
        self.evVPb.setGeometry(QtCore.QRect(248, 40, 40, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evVPb.sizePolicy().hasHeightForWidth())
        self.evVPb.setSizePolicy(sizePolicy)
        self.evVPb.setMinimumSize(QtCore.QSize(40, 0))
        self.evVPb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.evVPb.setObjectName(_fromUtf8("evVPb"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(148, 40, 97, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(151, 20, 96, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.evUPb = QtGui.QPushButton(self.frame_2)
        self.evUPb.setGeometry(QtCore.QRect(247, 20, 41, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evUPb.sizePolicy().hasHeightForWidth())
        self.evUPb.setSizePolicy(sizePolicy)
        self.evUPb.setMinimumSize(QtCore.QSize(38, 0))
        self.evUPb.setObjectName(_fromUtf8("evUPb"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(170, 60, 77, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.fftPb = QtGui.QPushButton(self.frame_2)
        self.fftPb.setGeometry(QtCore.QRect(249, 60, 41, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fftPb.sizePolicy().hasHeightForWidth())
        self.fftPb.setSizePolicy(sizePolicy)
        self.fftPb.setMinimumSize(QtCore.QSize(40, 0))
        self.fftPb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fftPb.setObjectName(_fromUtf8("fftPb"))
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(200, 80, 51, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.sLogPb = QtGui.QPushButton(self.frame_2)
        self.sLogPb.setGeometry(QtCore.QRect(250, 80, 40, 22))
        self.sLogPb.setMinimumSize(QtCore.QSize(40, 0))
        self.sLogPb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sLogPb.setObjectName(_fromUtf8("sLogPb"))
        self.logLimitCb = QtGui.QComboBox(self.frame_2)
        self.logLimitCb.setGeometry(QtCore.QRect(350, 100, 41, 24))
        self.logLimitCb.setObjectName(_fromUtf8("logLimitCb"))
        self.label_21 = QtGui.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(320, 100, 31, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(190, 100, 59, 15))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.wCorrelPb = QtGui.QPushButton(self.frame_2)
        self.wCorrelPb.setGeometry(QtCore.QRect(250, 100, 41, 24))
        self.wCorrelPb.setObjectName(_fromUtf8("wCorrelPb"))
        self.dataRestPb = QtGui.QPushButton(self.frame_2)
        self.dataRestPb.setGeometry(QtCore.QRect(90, 70, 40, 22))
        self.dataRestPb.setMinimumSize(QtCore.QSize(40, 0))
        self.dataRestPb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dataRestPb.setObjectName(_fromUtf8("dataRestPb"))
        self.label_31 = QtGui.QLabel(self.frame_2)
        self.label_31.setGeometry(QtCore.QRect(30, 70, 61, 20))
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_27 = QtGui.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(290, 20, 61, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.varsDistrPb = QtGui.QPushButton(self.frame_2)
        self.varsDistrPb.setGeometry(QtCore.QRect(350, 20, 40, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varsDistrPb.sizePolicy().hasHeightForWidth())
        self.varsDistrPb.setSizePolicy(sizePolicy)
        self.varsDistrPb.setMinimumSize(QtCore.QSize(40, 0))
        self.varsDistrPb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.varsDistrPb.setObjectName(_fromUtf8("varsDistrPb"))
        self.mMulitStartPb = QtGui.QPushButton(self.frame_2)
        self.mMulitStartPb.setGeometry(QtCore.QRect(90, 90, 40, 22))
        self.mMulitStartPb.setMinimumSize(QtCore.QSize(40, 0))
        self.mMulitStartPb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.mMulitStartPb.setObjectName(_fromUtf8("mMulitStartPb"))
        self.label_32 = QtGui.QLabel(self.frame_2)
        self.label_32.setGeometry(QtCore.QRect(10, 90, 81, 20))
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.logEd = QtGui.QPlainTextEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logEd.sizePolicy().hasHeightForWidth())
        self.logEd.setSizePolicy(sizePolicy)
        self.logEd.setReadOnly(True)
        self.logEd.setObjectName(_fromUtf8("logEd"))
        self.gridLayout.addWidget(self.logEd, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(400, 270))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.confSavePb = QtGui.QPushButton(self.frame)
        self.confSavePb.setGeometry(QtCore.QRect(320, 40, 51, 24))
        self.confSavePb.setObjectName(_fromUtf8("confSavePb"))
        self.NSb = QtGui.QSpinBox(self.frame)
        self.NSb.setGeometry(QtCore.QRect(320, 130, 71, 23))
        self.NSb.setObjectName(_fromUtf8("NSb"))
        self.LSb = QtGui.QSpinBox(self.frame)
        self.LSb.setGeometry(QtCore.QRect(320, 150, 71, 23))
        self.LSb.setObjectName(_fromUtf8("LSb"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(290, 130, 21, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(290, 150, 21, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(250, 80, 61, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.dataSzSb = QtGui.QSpinBox(self.frame)
        self.dataSzSb.setGeometry(QtCore.QRect(320, 80, 71, 23))
        self.dataSzSb.setObjectName(_fromUtf8("dataSzSb"))
        self.confOpenPb = QtGui.QPushButton(self.frame)
        self.confOpenPb.setGeometry(QtCore.QRect(340, 10, 31, 24))
        self.confOpenPb.setObjectName(_fromUtf8("confOpenPb"))
        self.configFileLe = QtGui.QLineEdit(self.frame)
        self.configFileLe.setGeometry(QtCore.QRect(70, 10, 261, 23))
        self.configFileLe.setReadOnly(True)
        self.configFileLe.setObjectName(_fromUtf8("configFileLe"))
        self.dataSourceSw = QtGui.QStackedWidget(self.frame)
        self.dataSourceSw.setGeometry(QtCore.QRect(20, 90, 221, 151))
        self.dataSourceSw.setFrameShape(QtGui.QFrame.Box)
        self.dataSourceSw.setObjectName(_fromUtf8("dataSourceSw"))
        self.csvPage = QtGui.QWidget()
        self.csvPage.setObjectName(_fromUtf8("csvPage"))
        self.label_17 = QtGui.QLabel(self.csvPage)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.csvFileLe = QtGui.QLineEdit(self.csvPage)
        self.csvFileLe.setGeometry(QtCore.QRect(10, 40, 121, 23))
        self.csvFileLe.setReadOnly(True)
        self.csvFileLe.setObjectName(_fromUtf8("csvFileLe"))
        self.csvFilePb = QtGui.QPushButton(self.csvPage)
        self.csvFilePb.setGeometry(QtCore.QRect(140, 40, 31, 24))
        self.csvFilePb.setObjectName(_fromUtf8("csvFilePb"))
        self.csvFileDataCb = QtGui.QComboBox(self.csvPage)
        self.csvFileDataCb.setGeometry(QtCore.QRect(10, 90, 151, 24))
        self.csvFileDataCb.setObjectName(_fromUtf8("csvFileDataCb"))
        self.csvFileDataCb.addItem(_fromUtf8(""))
        self.csvFileDataCb.addItem(_fromUtf8(""))
        self.csvFileDataCb.addItem(_fromUtf8(""))
        self.label_18 = QtGui.QLabel(self.csvPage)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 59, 15))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.dataSourceSw.addWidget(self.csvPage)
        self.linearPage = QtGui.QWidget()
        self.linearPage.setObjectName(_fromUtf8("linearPage"))
        self.label_19 = QtGui.QLabel(self.linearPage)
        self.label_19.setGeometry(QtCore.QRect(20, 50, 41, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.linearPage)
        self.label_20.setGeometry(QtCore.QRect(40, 80, 21, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.linearA1Sb = QtGui.QSpinBox(self.linearPage)
        self.linearA1Sb.setGeometry(QtCore.QRect(60, 50, 56, 23))
        self.linearA1Sb.setMinimum(-90)
        self.linearA1Sb.setMaximum(90)
        self.linearA1Sb.setObjectName(_fromUtf8("linearA1Sb"))
        self.linearA0Sb = QtGui.QDoubleSpinBox(self.linearPage)
        self.linearA0Sb.setGeometry(QtCore.QRect(60, 80, 56, 23))
        self.linearA0Sb.setObjectName(_fromUtf8("linearA0Sb"))
        self.label_23 = QtGui.QLabel(self.linearPage)
        self.label_23.setGeometry(QtCore.QRect(120, 50, 59, 15))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.dataSourceSw.addWidget(self.linearPage)
        self.sinusPage = QtGui.QWidget()
        self.sinusPage.setObjectName(_fromUtf8("sinusPage"))
        self.label_9 = QtGui.QLabel(self.sinusPage)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 41, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.sinusPage)
        self.label_10.setGeometry(QtCore.QRect(0, 50, 57, 14))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_13 = QtGui.QLabel(self.sinusPage)
        self.label_13.setGeometry(QtCore.QRect(0, 80, 57, 14))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.sinAmpSb = QtGui.QDoubleSpinBox(self.sinusPage)
        self.sinAmpSb.setGeometry(QtCore.QRect(60, 20, 62, 22))
        self.sinAmpSb.setObjectName(_fromUtf8("sinAmpSb"))
        self.sinPeriodSb = QtGui.QSpinBox(self.sinusPage)
        self.sinPeriodSb.setGeometry(QtCore.QRect(60, 50, 56, 22))
        self.sinPeriodSb.setMaximum(9999)
        self.sinPeriodSb.setObjectName(_fromUtf8("sinPeriodSb"))
        self.sinPhaseSb = QtGui.QSpinBox(self.sinusPage)
        self.sinPhaseSb.setGeometry(QtCore.QRect(60, 80, 56, 22))
        self.sinPhaseSb.setMaximum(360)
        self.sinPhaseSb.setSingleStep(5)
        self.sinPhaseSb.setObjectName(_fromUtf8("sinPhaseSb"))
        self.label_15 = QtGui.QLabel(self.sinusPage)
        self.label_15.setGeometry(QtCore.QRect(120, 80, 57, 14))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.dataSourceSw.addWidget(self.sinusPage)
        self.randomPage = QtGui.QWidget()
        self.randomPage.setObjectName(_fromUtf8("randomPage"))
        self.distribCb = QtGui.QComboBox(self.randomPage)
        self.distribCb.setGeometry(QtCore.QRect(90, 20, 111, 24))
        self.distribCb.setObjectName(_fromUtf8("distribCb"))
        self.distribCb.addItem(_fromUtf8(""))
        self.distribCb.addItem(_fromUtf8(""))
        self.label_24 = QtGui.QLabel(self.randomPage)
        self.label_24.setGeometry(QtCore.QRect(20, 20, 71, 20))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.randomMinSb = QtGui.QDoubleSpinBox(self.randomPage)
        self.randomMinSb.setGeometry(QtCore.QRect(100, 60, 62, 23))
        self.randomMinSb.setMinimum(-2.0)
        self.randomMinSb.setMaximum(2.0)
        self.randomMinSb.setSingleStep(0.1)
        self.randomMinSb.setObjectName(_fromUtf8("randomMinSb"))
        self.randomMaxSb = QtGui.QDoubleSpinBox(self.randomPage)
        self.randomMaxSb.setGeometry(QtCore.QRect(100, 90, 62, 23))
        self.randomMaxSb.setMinimum(-2.0)
        self.randomMaxSb.setMaximum(2.0)
        self.randomMaxSb.setSingleStep(0.1)
        self.randomMaxSb.setObjectName(_fromUtf8("randomMaxSb"))
        self.label_25 = QtGui.QLabel(self.randomPage)
        self.label_25.setGeometry(QtCore.QRect(70, 60, 31, 20))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.randomPage)
        self.label_26.setGeometry(QtCore.QRect(70, 90, 31, 20))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.randomCacheChb = QtGui.QCheckBox(self.randomPage)
        self.randomCacheChb.setGeometry(QtCore.QRect(70, 120, 89, 21))
        self.randomCacheChb.setChecked(True)
        self.randomCacheChb.setObjectName(_fromUtf8("randomCacheChb"))
        self.dataSourceSw.addWidget(self.randomPage)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.dataSourceSw.addWidget(self.page_2)
        self.sourcNumLb = QtGui.QLabel(self.frame)
        self.sourcNumLb.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.sourcNumLb.setObjectName(_fromUtf8("sourcNumLb"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.calcPb = QtGui.QPushButton(self.frame)
        self.calcPb.setGeometry(QtCore.QRect(340, 240, 41, 24))
        self.calcPb.setObjectName(_fromUtf8("calcPb"))
        self.sourceTypeCb = QtGui.QComboBox(self.frame)
        self.sourceTypeCb.setGeometry(QtCore.QRect(60, 60, 151, 24))
        self.sourceTypeCb.setObjectName(_fromUtf8("sourceTypeCb"))
        self.predictSb = QtGui.QSpinBox(self.frame)
        self.predictSb.setGeometry(QtCore.QRect(320, 180, 71, 24))
        self.predictSb.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.predictSb.setProperty("value", 1)
        self.predictSb.setObjectName(_fromUtf8("predictSb"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(270, 180, 51, 24))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.csvFileOffsetSb = QtGui.QSpinBox(self.frame)
        self.csvFileOffsetSb.setGeometry(QtCore.QRect(320, 100, 71, 23))
        self.csvFileOffsetSb.setObjectName(_fromUtf8("csvFileOffsetSb"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(270, 100, 41, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.combinedSrcLbl = QtGui.QLabel(self.frame)
        self.combinedSrcLbl.setGeometry(QtCore.QRect(220, 60, 91, 16))
        self.combinedSrcLbl.setText(_fromUtf8(""))
        self.combinedSrcLbl.setObjectName(_fromUtf8("combinedSrcLbl"))
        self.calcRankCb = QtGui.QCheckBox(self.frame)
        self.calcRankCb.setGeometry(QtCore.QRect(300, 210, 85, 21))
        self.calcRankCb.setObjectName(_fromUtf8("calcRankCb"))
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.dataSourceSw.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "SSA", None))
        self.label.setText(_translate("Dialog", "Show", None))
        self.label_4.setText(_translate("Dialog", "Data", None))
        self.dataPb.setText(_translate("Dialog", "...", None))
        self.evVPb.setText(_translate("Dialog", "...", None))
        self.label_5.setText(_translate("Dialog", "Eigenvectors V", None))
        self.label_6.setText(_translate("Dialog", "Eigenvectors U", None))
        self.evUPb.setText(_translate("Dialog", "...", None))
        self.label_7.setText(_translate("Dialog", "FFT decomp", None))
        self.fftPb.setText(_translate("Dialog", "...", None))
        self.label_16.setText(_translate("Dialog", "Log(S)", None))
        self.sLogPb.setText(_translate("Dialog", "...", None))
        self.label_21.setText(_translate("Dialog", "X lim", None))
        self.label_22.setText(_translate("Dialog", "w-correl", None))
        self.wCorrelPb.setText(_translate("Dialog", "...", None))
        self.dataRestPb.setText(_translate("Dialog", "...", None))
        self.label_31.setText(_translate("Dialog", "data rest", None))
        self.label_27.setText(_translate("Dialog", "Vals distr", None))
        self.varsDistrPb.setText(_translate("Dialog", "...", None))
        self.mMulitStartPb.setText(_translate("Dialog", "...", None))
        self.label_32.setText(_translate("Dialog", "M-multistart", None))
        self.confSavePb.setText(_translate("Dialog", "Save", None))
        self.label_3.setText(_translate("Dialog", "N", None))
        self.label_11.setText(_translate("Dialog", "L", None))
        self.label_12.setText(_translate("Dialog", "Data size", None))
        self.confOpenPb.setText(_translate("Dialog", "...", None))
        self.label_17.setText(_translate("Dialog", "File", None))
        self.csvFilePb.setText(_translate("Dialog", "...", None))
        self.csvFileDataCb.setItemText(0, _translate("Dialog", "High", None))
        self.csvFileDataCb.setItemText(1, _translate("Dialog", "Low", None))
        self.csvFileDataCb.setItemText(2, _translate("Dialog", "(High+Low)/2", None))
        self.label_18.setText(_translate("Dialog", "Data", None))
        self.label_19.setText(_translate("Dialog", "angle", None))
        self.label_20.setText(_translate("Dialog", "y0", None))
        self.label_23.setText(_translate("Dialog", "-90..+90", None))
        self.label_9.setText(_translate("Dialog", "amp", None))
        self.label_10.setText(_translate("Dialog", "period", None))
        self.label_13.setText(_translate("Dialog", "phase", None))
        self.label_15.setText(_translate("Dialog", "(0..360)", None))
        self.distribCb.setItemText(0, _translate("Dialog", "normal", None))
        self.distribCb.setItemText(1, _translate("Dialog", "uniform", None))
        self.label_24.setText(_translate("Dialog", "distribution", None))
        self.label_25.setText(_translate("Dialog", "min", None))
        self.label_26.setText(_translate("Dialog", "max", None))
        self.randomCacheChb.setToolTip(_translate("Dialog", "Fix data on first calculation", None))
        self.randomCacheChb.setText(_translate("Dialog", "use cache", None))
        self.sourcNumLb.setText(_translate("Dialog", "Source", None))
        self.label_2.setText(_translate("Dialog", "Config", None))
        self.calcPb.setText(_translate("Dialog", "Calc", None))
        self.label_8.setText(_translate("Dialog", "Predict", None))
        self.label_14.setText(_translate("Dialog", "Offset", None))
        self.calcRankCb.setText(_translate("Dialog", "calc rank", None))

